### ISSUE TITLE
Alveary Mutator Not Guaranteeing Pure Mutation 

### ISSUE THREAD

**Issue by DragonScales4** [Chocohead/Binnie-Patcher#10] opened 2016-03-25 06:34 UTC
Not sure if this is the right place but here goes:

With 3 Mutators each with an Eye of Ender it only seems to affect the mutation chance of certain species. For example, Noble + Diligent is guaranteed to give Ancient, but Noble + Cultivated usually gives a hybrid, like it does by default, with the same setup.  Not sure if it has anything to do with the fact that Ancient if from Extra Bees, but it seems to behave with most of Extra Bees species. 

Running on Infinity Evolved 2.4.2 with Binnie Patcher updated to 1.6. 

Hopefully that's enough to explain what's happening. Kinda new to this. 

Thanks for your time.

**Comment by Chocohead** [comment] 2016-03-26 22:27
Interesting, I'll take a look.

**Comment by Chocohead** [comment] 2016-03-27 01:15
What happens when you try it with Forestry 3 with Binnie's Mods? The logic that handles it should work for any bee the same way, so it might be working as Binnie intended.

**Comment by DragonScales4** [comment] 2016-03-27 06:38
So after rolling Infinity back to 2.3.5, the last one to have Forestry 3, and testing the same setup, I haven't had any problems. 

If it helps any, on the version with Forestry 4 using a bunch of Frame Housings with Soul/ Metabolic Frames does the trick. So getting this fixed isn't a huge deal.

**Comment by DragonScales4** [comment] 2016-03-27 06:41
If there is something else you'd like me to test, just let me know.

**Comment by Chocohead** [comment] 2016-03-27 16:02
It's definitely effecting the mutation chance, I guess it's just less predictable for mutations that could result in more than one bee. At least frames can be used as a work around I suppose.

**Comment by ic0ns** [comment] 2016-04-01 13:11
i can confirm this issue, tested with 3 mutators and 3 netherstars still normal mutation chances

**Comment by ghost** [comment] 2016-05-05 19:35
It seems like the Mutator consumes items regardless of them being registered as mutator or not (registration is done in binnie.extrabees.apiary.ModuleApiary.class). So maybe the naming convention changed in forge (or IC2).

PS: ic0ons, Netherstars don't work anymore.

**Comment by Flexico** [comment] 2016-05-28 03:13
What all items do work in the mutator? I was planning to use plutonium, and was wondering about the ideal number of mutators to use. So, are mutators not working at all with Forestry 4?

**Comment by Chocohead** [comment] 2017-04-12 14:39
Should be fixed next version.

**Closed as completed by Chocohead** 2017-04-12 14:39 UTC
Labels: Fixed
